services:
  mc-radar:
    container_name: mcradar
    image: local-interloper/mcradar
    build:
      context: ./mcradar

    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    networks:
      - mcradar-network

    develop:
      watch:
        - action: rebuild
          path: ./mcradar

  api:
    container_name: mcradar-api
    image: local-interloper/mcradar-api
    build:
      context: ./mcradar-api

    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    networks:
      - mcradar-network

    develop:
      watch:
        - action: rebuild
          path: ./mcradar-api

  db:
    container_name: mcradar-db
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 128mb
    command: -c 'max_connections=${POSTGRES_MAX_CONNECTIONS}'

    env_file: .env

    volumes:
      - "mcradar-db-volume:/var/lib/postgresql/18/docker"

    networks:
      - mcradar-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mcradar-db-volume:


networks:
  mcradar-network:
